//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Proposals = new HashSet<Proposal>();
            this.SavedPosts = new HashSet<SavedPost>();
        }
    
        public int ID { get; set; }
        public int ClientID { get; set; }
        [Required(ErrorMessage = "Description is Required")]
        public string Description { get; set; }
        public string Type { get; set; }
        [Required(ErrorMessage = "Budget is Required")]
        public int Budget { get; set; }
        public Nullable<int> Rate { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> NumbrOfProposals { get; set; }
        public bool Accept { get; set; }
        public bool Remove { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal> Proposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedPost> SavedPosts { get; set; }

       
    }
    public class listofposts
    {
        public List<Post> Result { get; set; }
    }

    public enum JopType
    {
        Fixed,
        Hourly
    }
}
