//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeLance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal
    {
        public int PropID { get; set; }
        public int PostID { get; set; }
        public int UserID { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }

    public class listofproposals
    {
        public List<User> Result { get; set; }
        public int PostID { get; set; }
    }
}
